USE [master]
GO
/****** Object:  Database [ECOM]    Script Date: 12/10/2022 10:46:57 PM ******/
CREATE DATABASE [ECOM]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ECOM', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\ECOM.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ECOM_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\ECOM_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [ECOM] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ECOM].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ECOM] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ECOM] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ECOM] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ECOM] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ECOM] SET ARITHABORT OFF 
GO
ALTER DATABASE [ECOM] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ECOM] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ECOM] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ECOM] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ECOM] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ECOM] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ECOM] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ECOM] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ECOM] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ECOM] SET  DISABLE_BROKER 
GO
ALTER DATABASE [ECOM] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ECOM] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ECOM] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ECOM] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ECOM] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ECOM] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ECOM] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ECOM] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [ECOM] SET  MULTI_USER 
GO
ALTER DATABASE [ECOM] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ECOM] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ECOM] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ECOM] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [ECOM] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [ECOM] SET QUERY_STORE = OFF
GO
USE [ECOM]
GO
/****** Object:  Table [dbo].[CATEGORES]    Script Date: 12/10/2022 10:46:57 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CATEGORES](
	[IdCAT] [int] IDENTITY(1,1) NOT NULL,
	[NamCAT] [varchar](200) NULL,
	[DescriptionCAT] [varchar](200) NULL,
 CONSTRAINT [PK_CATEGORES] PRIMARY KEY CLUSTERED 
(
	[IdCAT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CUSTOMERS]    Script Date: 12/10/2022 10:46:57 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CUSTOMERS](
	[IdCustomer] [int] IDENTITY(1,1) NOT NULL,
	[FirstName] [varchar](20) NULL,
	[LastName] [varchar](20) NULL,
	[phone] [varchar](20) NULL,
	[email] [varchar](20) NULL,
	[city] [varchar](20) NULL,
	[img] [image] NULL,
 CONSTRAINT [PK_CUSTOMERS] PRIMARY KEY CLUSTERED 
(
	[IdCustomer] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ECOM_USERS]    Script Date: 12/10/2022 10:46:57 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ECOM_USERS](
	[IdUser] [int] IDENTITY(1,1) NOT NULL,
	[userName] [varchar](20) NOT NULL,
	[PassWorde] [varchar](10) NOT NULL,
	[TypeUser] [varchar](20) NOT NULL,
	[img] [image] NULL,
 CONSTRAINT [PK_ECOM_USERS] PRIMARY KEY CLUSTERED 
(
	[IdUser] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ORDERS]    Script Date: 12/10/2022 10:46:57 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ORDERS](
	[IdOrder] [int] IDENTITY(1,1) NOT NULL,
	[DateOrder] [datetime] NULL,
	[IdCustomer] [int] NULL,
 CONSTRAINT [PK_ORDERS] PRIMARY KEY CLUSTERED 
(
	[IdOrder] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ORDERS_DETAILS]    Script Date: 12/10/2022 10:46:57 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ORDERS_DETAILS](
	[IdProduct] [int] NOT NULL,
	[IdOrder] [int] NOT NULL,
	[Qte] [int] NOT NULL,
 CONSTRAINT [PK_ORDERS_DETAILS] PRIMARY KEY CLUSTERED 
(
	[IdProduct] ASC,
	[IdOrder] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRODUCTS]    Script Date: 12/10/2022 10:46:57 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRODUCTS](
	[IdProduct] [int] IDENTITY(1,1) NOT NULL,
	[NamProduct] [varchar](20) NULL,
	[description] [varchar](300) NULL,
	[QteInStock] [int] NULL,
	[Price] [float] NULL,
	[img1] [image] NULL,
	[img2] [image] NULL,
	[img3] [image] NULL,
	[IdCAT] [int] NULL,
 CONSTRAINT [PK_PRODUCTS] PRIMARY KEY CLUSTERED 
(
	[IdProduct] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[ORDERS]  WITH CHECK ADD  CONSTRAINT [FK_ORDERS_CUSTOMERS] FOREIGN KEY([IdCustomer])
REFERENCES [dbo].[CUSTOMERS] ([IdCustomer])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[ORDERS] CHECK CONSTRAINT [FK_ORDERS_CUSTOMERS]
GO
ALTER TABLE [dbo].[ORDERS_DETAILS]  WITH CHECK ADD  CONSTRAINT [FK_ORDERS_DETAILS_ORDERS] FOREIGN KEY([IdOrder])
REFERENCES [dbo].[ORDERS] ([IdOrder])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[ORDERS_DETAILS] CHECK CONSTRAINT [FK_ORDERS_DETAILS_ORDERS]
GO
ALTER TABLE [dbo].[ORDERS_DETAILS]  WITH CHECK ADD  CONSTRAINT [FK_ORDERS_DETAILS_PRODUCTS] FOREIGN KEY([IdProduct])
REFERENCES [dbo].[PRODUCTS] ([IdProduct])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[ORDERS_DETAILS] CHECK CONSTRAINT [FK_ORDERS_DETAILS_PRODUCTS]
GO
ALTER TABLE [dbo].[PRODUCTS]  WITH CHECK ADD  CONSTRAINT [FK_PRODUCTS_CATEGORES] FOREIGN KEY([IdCAT])
REFERENCES [dbo].[CATEGORES] ([IdCAT])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[PRODUCTS] CHECK CONSTRAINT [FK_PRODUCTS_CATEGORES]
GO
/****** Object:  StoredProcedure [dbo].[AddProduct]    Script Date: 12/10/2022 10:46:57 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE proc [dbo].[AddProduct] 
@pname varchar(20),@desc varchar(300),@qte int,@price float,@img1 image,@img2 image,@img3 image,@idcat INT 
as
begin

INSERT INTO [dbo].[PRODUCTS]
           ([NamProduct]
		   ,[description]
           ,[QteInStock]
           ,[Price]
           ,[img1]
           ,[img2]
           ,[img3]
           ,[IdCAT])
     VALUES
           (@pname
		   ,@desc
           ,@qte
           ,@price
           ,@img1
           ,@img2
           ,@img3
           ,@idcat)
 end
GO
/****** Object:  StoredProcedure [dbo].[GET_ALL_PRODUCTS]    Script Date: 12/10/2022 10:46:57 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create proc [dbo].[GET_ALL_PRODUCTS]
as
SELECT 
      [NamProduct]
      ,[description]
      ,[QteInStock]
      ,[Price]    
      ,[NamCAT]
  FROM [dbo].[PRODUCTS],CATEGORES
  where PRODUCTS.IdCAT=CATEGORES.IdCAT
GO
/****** Object:  StoredProcedure [dbo].[GetAllGategores]    Script Date: 12/10/2022 10:46:57 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create proc [dbo].[GetAllGategores] as
select idCAT , NamCAT from CATEGORES
GO
/****** Object:  StoredProcedure [dbo].[SP_LOGIN]    Script Date: 12/10/2022 10:46:57 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create proc [dbo].[SP_LOGIN]
@user varchar(20),@PASS VARCHAR(10)
AS
SELECT* FROM ECOM_USERS 
WHERE userName=@user and PassWorde=@PASS
GO
USE [master]
GO
ALTER DATABASE [ECOM] SET  READ_WRITE 
GO
